//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/yndd/nddo-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraInfrastructure) DeepCopyInto(out *InfraInfrastructure) {
	*out = *in
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.ASpool != nil {
		in, out := &in.ASpool, &out.ASpool
		*out = new(InfraInfrastructureASPool)
		(*in).DeepCopyInto(*out)
	}
	if in.AS != nil {
		in, out := &in.AS, &out.AS
		*out = new(uint32)
		**out = **in
	}
	if in.Cidr != nil {
		in, out := &in.Cidr, &out.Cidr
		*out = new(InfraInfrastructureCidr)
		(*in).DeepCopyInto(*out)
	}
	if in.AddressingScheme != nil {
		in, out := &in.AddressingScheme, &out.AddressingScheme
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.OverlayProtocol != nil {
		in, out := &in.OverlayProtocol, &out.OverlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UnderlayProtocol != nil {
		in, out := &in.UnderlayProtocol, &out.UnderlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InterfaceSelector != nil {
		in, out := &in.InterfaceSelector, &out.InterfaceSelector
		*out = make([]*v1.InterfaceSelector, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.InterfaceSelector)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraInfrastructure.
func (in *InfraInfrastructure) DeepCopy() *InfraInfrastructure {
	if in == nil {
		return nil
	}
	out := new(InfraInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraInfrastructureASPool) DeepCopyInto(out *InfraInfrastructureASPool) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(uint32)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraInfrastructureASPool.
func (in *InfraInfrastructureASPool) DeepCopy() *InfraInfrastructureASPool {
	if in == nil {
		return nil
	}
	out := new(InfraInfrastructureASPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfraInfrastructureCidr) DeepCopyInto(out *InfraInfrastructureCidr) {
	*out = *in
	if in.IslCidrIpv4 != nil {
		in, out := &in.IslCidrIpv4, &out.IslCidrIpv4
		*out = new(string)
		**out = **in
	}
	if in.IslCidrIpv6 != nil {
		in, out := &in.IslCidrIpv6, &out.IslCidrIpv6
		*out = new(string)
		**out = **in
	}
	if in.LoopbackCidrIpv4 != nil {
		in, out := &in.LoopbackCidrIpv4, &out.LoopbackCidrIpv4
		*out = new(string)
		**out = **in
	}
	if in.LoopbackCidrIpv6 != nil {
		in, out := &in.LoopbackCidrIpv6, &out.LoopbackCidrIpv6
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfraInfrastructureCidr.
func (in *InfraInfrastructureCidr) DeepCopy() *InfraInfrastructureCidr {
	if in == nil {
		return nil
	}
	out := new(InfraInfrastructureCidr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Infrastructure) DeepCopyInto(out *Infrastructure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Infrastructure.
func (in *Infrastructure) DeepCopy() *Infrastructure {
	if in == nil {
		return nil
	}
	out := new(Infrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Infrastructure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureList) DeepCopyInto(out *InfrastructureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Infrastructure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureList.
func (in *InfrastructureList) DeepCopy() *InfrastructureList {
	if in == nil {
		return nil
	}
	out := new(InfrastructureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfrastructureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureSpec) DeepCopyInto(out *InfrastructureSpec) {
	*out = *in
	out.ResourceSpec = in.ResourceSpec
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(InfraInfrastructure)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureSpec.
func (in *InfrastructureSpec) DeepCopy() *InfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(InfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructureStatus) DeepCopyInto(out *InfrastructureStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	in.OdaInfo.DeepCopyInto(&out.OdaInfo)
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = new(NddoinfrastructureInfrastructure)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructureStatus.
func (in *InfrastructureStatus) DeepCopy() *InfrastructureStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nddoinfrastructure) DeepCopyInto(out *Nddoinfrastructure) {
	*out = *in
	if in.Infrastructure != nil {
		in, out := &in.Infrastructure, &out.Infrastructure
		*out = make([]*NddoinfrastructureInfrastructure, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoinfrastructureInfrastructure)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nddoinfrastructure.
func (in *Nddoinfrastructure) DeepCopy() *Nddoinfrastructure {
	if in == nil {
		return nil
	}
	out := new(Nddoinfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoinfrastructureInfrastructure) DeepCopyInto(out *NddoinfrastructureInfrastructure) {
	*out = *in
	if in.AddressingScheme != nil {
		in, out := &in.AddressingScheme, &out.AddressingScheme
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.OverlayProtocol != nil {
		in, out := &in.OverlayProtocol, &out.OverlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddoinfrastructureInfrastructureState)
		(*in).DeepCopyInto(*out)
	}
	if in.UnderlayProtocol != nil {
		in, out := &in.UnderlayProtocol, &out.UnderlayProtocol
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoinfrastructureInfrastructure.
func (in *NddoinfrastructureInfrastructure) DeepCopy() *NddoinfrastructureInfrastructure {
	if in == nil {
		return nil
	}
	out := new(NddoinfrastructureInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoinfrastructureInfrastructureState) DeepCopyInto(out *NddoinfrastructureInfrastructureState) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = new(string)
		**out = **in
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = make([]*NddoinfrastructureInfrastructureStateNode, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoinfrastructureInfrastructureStateNode)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = make([]*NddoinfrastructureInfrastructureStateLink, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoinfrastructureInfrastructureStateLink)
				**out = **in
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoinfrastructureInfrastructureState.
func (in *NddoinfrastructureInfrastructureState) DeepCopy() *NddoinfrastructureInfrastructureState {
	if in == nil {
		return nil
	}
	out := new(NddoinfrastructureInfrastructureState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoinfrastructureInfrastructureStateLink) DeepCopyInto(out *NddoinfrastructureInfrastructureStateLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoinfrastructureInfrastructureStateLink.
func (in *NddoinfrastructureInfrastructureStateLink) DeepCopy() *NddoinfrastructureInfrastructureStateLink {
	if in == nil {
		return nil
	}
	out := new(NddoinfrastructureInfrastructureStateLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoinfrastructureInfrastructureStateNode) DeepCopyInto(out *NddoinfrastructureInfrastructureStateNode) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = make([]*NddoinfrastructureInfrastructureStateNodeEndpoint, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddoinfrastructureInfrastructureStateNodeEndpoint)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoinfrastructureInfrastructureStateNode.
func (in *NddoinfrastructureInfrastructureStateNode) DeepCopy() *NddoinfrastructureInfrastructureStateNode {
	if in == nil {
		return nil
	}
	out := new(NddoinfrastructureInfrastructureStateNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddoinfrastructureInfrastructureStateNodeEndpoint) DeepCopyInto(out *NddoinfrastructureInfrastructureStateNodeEndpoint) {
	*out = *in
	if in.Lag != nil {
		in, out := &in.Lag, &out.Lag
		*out = new(bool)
		**out = **in
	}
	if in.LagSubLink != nil {
		in, out := &in.LagSubLink, &out.LagSubLink
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddoinfrastructureInfrastructureStateNodeEndpoint.
func (in *NddoinfrastructureInfrastructureStateNodeEndpoint) DeepCopy() *NddoinfrastructureInfrastructureStateNodeEndpoint {
	if in == nil {
		return nil
	}
	out := new(NddoinfrastructureInfrastructureStateNodeEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.InfraNddoinfrastructure != nil {
		in, out := &in.InfraNddoinfrastructure, &out.InfraNddoinfrastructure
		*out = new(Nddoinfrastructure)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}
